import colors from "tailwindcss/colors";

export const classNames = [
  {
    id: "red",
    color: colors.red,
    background: "bg-gradient-to-br from-red-50 to-red-100",
    title: "text-red-800",
    shadow: "shadow-md shadow-red-600/10 ring-1 ring-red-800/5",
    focusWithin: "focus-within:outline-red-600",
    focusVisible: "focus-visible:outline-red-600",
  },
  {
    id: "orange",
    color: colors.orange,
    background: "bg-gradient-to-br from-orange-50 to-orange-100",
    title: "text-orange-800",
    shadow: "shadow-md shadow-orange-600/10 ring-1 ring-orange-800/5",
    focusWithin: "focus-within:outline-orange-600",
    focusVisible: "focus-visible:outline-orange-600",
  },
  {
    id: "amber",
    color: colors.amber,
    background: "bg-gradient-to-br from-amber-50 to-amber-100",
    title: "text-amber-800",
    shadow: "shadow-md shadow-amber-600/10 ring-1 ring-amber-800/5",
    focusWithin: "focus-within:outline-amber-600",
    focusVisible: "focus-visible:outline-amber-600",
  },
  {
    id: "yellow",
    color: colors.yellow,
    background: "bg-gradient-to-br from-yellow-50 to-yellow-100",
    title: "text-yellow-800",
    shadow: "shadow-md shadow-yellow-600/10 ring-1 ring-yellow-800/5",
    focusWithin: "focus-within:outline-yellow-600",
    focusVisible: "focus-visible:outline-yellow-600",
  },
  {
    id: "lime",
    color: colors.lime,
    background: "bg-gradient-to-br from-lime-50 to-lime-100",
    title: "text-lime-800",
    shadow: "shadow-md shadow-lime-600/10 ring-1 ring-lime-800/5",
    focusWithin: "focus-within:outline-lime-600",
    focusVisible: "focus-visible:outline-lime-600",
  },
  {
    id: "green",
    color: colors.green,
    background: "bg-gradient-to-br from-green-50 to-green-100",
    title: "text-green-800",
    shadow: "shadow-md shadow-green-600/10 ring-1 ring-green-800/5",
    focusWithin: "focus-within:outline-green-600",
    focusVisible: "focus-visible:outline-green-600",
  },
  {
    id: "emerald",
    color: colors.emerald,
    background: "bg-gradient-to-br from-emerald-50 to-emerald-100",
    title: "text-emerald-800",
    shadow: "shadow-md shadow-emerald-600/10 ring-1 ring-emerald-800/5",
    focusWithin: "focus-within:outline-emerald-600",
    focusVisible: "focus-visible:outline-emerald-600",
  },
  {
    id: "teal",
    color: colors.teal,
    background: "bg-gradient-to-br from-teal-50 to-teal-100",
    title: "text-teal-800",
    shadow: "shadow-md shadow-teal-600/10 ring-1 ring-teal-800/5",
    focusWithin: "focus-within:outline-teal-600",
    focusVisible: "focus-visible:outline-teal-600",
  },
  {
    id: "cyan",
    color: colors.cyan,
    background: "bg-gradient-to-br from-cyan-50 to-cyan-100",
    title: "text-cyan-800",
    shadow: "shadow-md shadow-cyan-600/10 ring-1 ring-cyan-800/5",
    focusWithin: "focus-within:outline-cyan-600",
    focusVisible: "focus-visible:outline-cyan-600",
  },
  {
    id: "sky",
    color: colors.sky,
    background: "bg-gradient-to-br from-sky-50 to-sky-100",
    title: "text-sky-800",
    shadow: "shadow-md shadow-sky-600/10 ring-1 ring-sky-800/5",
    focusWithin: "focus-within:outline-sky-600",
    focusVisible: "focus-visible:outline-sky-600",
  },
  {
    id: "blue",
    color: colors.blue,
    background: "bg-gradient-to-br from-blue-50 to-blue-100",
    title: "text-blue-800",
    shadow: "shadow-md shadow-blue-600/10 ring-1 ring-blue-800/5",
    focusWithin: "focus-within:outline-blue-600",
    focusVisible: "focus-visible:outline-blue-600",
  },
  {
    id: "indigo",
    color: colors.indigo,
    background: "bg-gradient-to-br from-indigo-50 to-indigo-100",
    title: "text-indigo-800",
    shadow: "shadow-md shadow-indigo-600/10 ring-1 ring-indigo-800/5",
    focusWithin: "focus-within:outline-indigo-600",
    focusVisible: "focus-visible:outline-indigo-600",
  },
  {
    id: "violet",
    color: colors.violet,
    background: "bg-gradient-to-br from-violet-50 to-violet-100",
    title: "text-violet-800",
    shadow: "shadow-md shadow-violet-600/10 ring-1 ring-violet-800/5",
    focusWithin: "focus-within:outline-violet-600",
    focusVisible: "focus-visible:outline-violet-600",
  },
  {
    id: "purple",
    color: colors.purple,
    background: "bg-gradient-to-br from-purple-50 to-purple-100",
    title: "text-purple-800",
    shadow: "shadow-md shadow-purple-600/10 ring-1 ring-purple-800/5",
    focusWithin: "focus-within:outline-purple-600",
    focusVisible: "focus-visible:outline-purple-600",
  },
  {
    id: "fuschia",
    color: colors.fuchsia,
    background: "bg-gradient-to-br from-fuchsia-50 to-fuchsia-100",
    title: "text-fuchsia-800",
    shadow: "shadow-md shadow-fuchsia-600/10 ring-1 ring-fuchsia-800/5",
    focusWithin: "focus-within:outline-fuchsia-600",
    focusVisible: "focus-visible:outline-fuchsia-600",
  },
  {
    id: "pink",
    color: colors.pink,
    background: "bg-gradient-to-br from-pink-50 to-pink-100",
    title: "text-pink-800",
    shadow: "shadow-md shadow-pink-600/10 ring-1 ring-pink-800/5",
    focusWithin: "focus-within:outline-pink-600",
    focusVisible: "focus-visible:outline-pink-600",
  },
  {
    id: "rose",
    color: colors.rose,
    background: "bg-gradient-to-br from-rose-50 to-rose-100",
    title: "text-rose-800",
    shadow: "shadow-md shadow-rose-600/10 ring-1 ring-rose-800/5",
    focusWithin: "focus-within:outline-rose-600",
    focusVisible: "focus-visible:outline-rose-600",
  },
];
