import { normalizeIntimacyProcedureSlug } from "lib/intimacy-aliases";

export type CatalogKind = "product" | "procedure";
export type PricingMode = "fixed" | "quantity" | "increment_credit";
export type FulfillmentMode = "pickup" | "appointment";

export type CatalogItemConfig = {
  slug: string;
  kind: CatalogKind;
  name: string;
  shortDescription: string;
  pricingMode: PricingMode;
  unitAmountCents: number;
  currency: "usd";
  displayPrice: string;
  quantityLabel: string;
  minQuantity: number;
  maxQuantity: number;
  requiresScheduling: boolean;
  fulfillment: FulfillmentMode;
  imagePath?: string;
  stripeProductKey: string;
  stripePriceLookupKey: string;
  schedulingCategory?: "consult" | "paid_procedure";
  customerNote?: string;
};

export const COMMERCE_CATALOG: CatalogItemConfig[] = [
  {
    slug: "o-shot",
    kind: "procedure",
    name: "O-Shot",
    shortDescription: "Full upfront payment for one treatment visit.",
    pricingMode: "fixed",
    unitAmountCents: 120000,
    currency: "usd",
    displayPrice: "$1,200",
    quantityLabel: "treatment",
    minQuantity: 1,
    maxQuantity: 10,
    requiresScheduling: true,
    fulfillment: "appointment",
    imagePath: "/procedure/grapefruit.jpg",
    stripeProductKey: "wms_procedure_o_shot",
    stripePriceLookupKey: "wms_procedure_o_shot_1200_v1",
  },
  {
    slug: "p-shot",
    kind: "procedure",
    name: "P-Shot",
    shortDescription: "Full upfront payment for one treatment visit.",
    pricingMode: "fixed",
    unitAmountCents: 190000,
    currency: "usd",
    displayPrice: "$1,900",
    quantityLabel: "treatment",
    minQuantity: 1,
    maxQuantity: 10,
    requiresScheduling: true,
    fulfillment: "appointment",
    imagePath: "/procedure/banana.jpg",
    stripeProductKey: "wms_procedure_p_shot",
    stripePriceLookupKey: "wms_procedure_p_shot_1900_v1",
  },
  {
    slug: "prp-breast-lift",
    kind: "procedure",
    name: "PRP Breast Lift",
    shortDescription: "Full upfront payment for one treatment visit.",
    pricingMode: "fixed",
    unitAmountCents: 180000,
    currency: "usd",
    displayPrice: "$1,800",
    quantityLabel: "treatment",
    minQuantity: 1,
    maxQuantity: 10,
    requiresScheduling: true,
    fulfillment: "appointment",
    imagePath: "/procedure/breast.png",
    stripeProductKey: "wms_procedure_prp_breast_lift",
    stripePriceLookupKey: "wms_procedure_prp_breast_lift_1800_v1",
  },
  {
    slug: "prp-hair-restoration",
    kind: "procedure",
    name: "PRP Hair Restoration",
    shortDescription: "Charged per treatment session.",
    pricingMode: "quantity",
    unitAmountCents: 60000,
    currency: "usd",
    displayPrice: "$600 per treatment",
    quantityLabel: "treatment",
    minQuantity: 1,
    maxQuantity: 12,
    requiresScheduling: true,
    fulfillment: "appointment",
    imagePath: "/procedure/hair.jpg",
    stripeProductKey: "wms_procedure_prp_hair_restoration",
    stripePriceLookupKey: "wms_procedure_prp_hair_restoration_600_v1",
  },
  {
    slug: "prp-facial",
    kind: "procedure",
    name: "PRP Facial",
    shortDescription: "Full upfront payment for one treatment visit.",
    pricingMode: "fixed",
    unitAmountCents: 60000,
    currency: "usd",
    displayPrice: "$600",
    quantityLabel: "treatment",
    minQuantity: 1,
    maxQuantity: 10,
    requiresScheduling: true,
    fulfillment: "appointment",
    imagePath: "/procedure/facial.png",
    stripeProductKey: "wms_procedure_prp_facial",
    stripePriceLookupKey: "wms_procedure_prp_facial_600_v1",
  },
  {
    slug: "prp-face-lift",
    kind: "procedure",
    name: "PRP Face Lift",
    shortDescription: "Full upfront payment for one treatment visit.",
    pricingMode: "fixed",
    unitAmountCents: 150000,
    currency: "usd",
    displayPrice: "$1,500",
    quantityLabel: "treatment",
    minQuantity: 1,
    maxQuantity: 10,
    requiresScheduling: true,
    fulfillment: "appointment",
    imagePath: "/procedure/facelift.png",
    stripeProductKey: "wms_procedure_prp_face_lift",
    stripePriceLookupKey: "wms_procedure_prp_face_lift_1500_v1",
  },
  {
    slug: "joint-restoration",
    kind: "procedure",
    name: "Joint Restoration",
    shortDescription: "Full upfront payment for one treatment visit.",
    pricingMode: "fixed",
    unitAmountCents: 80000,
    currency: "usd",
    displayPrice: "$800",
    quantityLabel: "treatment",
    minQuantity: 1,
    maxQuantity: 10,
    requiresScheduling: true,
    fulfillment: "appointment",
    imagePath: "/procedure/wrist.jpg",
    stripeProductKey: "wms_procedure_joint_restoration",
    stripePriceLookupKey: "wms_procedure_joint_restoration_800_v1",
  },
  {
    slug: "botox",
    kind: "procedure",
    name: "Botox",
    shortDescription: "Prepaid treatment credit sold in $250 blocks.",
    pricingMode: "increment_credit",
    unitAmountCents: 25000,
    currency: "usd",
    displayPrice: "$250 increments",
    quantityLabel: "$250 block",
    minQuantity: 1,
    maxQuantity: 4,
    requiresScheduling: true,
    fulfillment: "appointment",
    imagePath: "/procedure/botox.png",
    stripeProductKey: "wms_procedure_botox",
    stripePriceLookupKey: "wms_procedure_botox_block_250_v1",
    customerNote:
      "Botox is prepaid online in $250 blocks. The amount is applied to your treatment and any unused value remains as account credit.",
  },
  {
    slug: "xeomin",
    kind: "procedure",
    name: "Xeomin",
    shortDescription: "Prepaid treatment credit sold in $250 blocks.",
    pricingMode: "increment_credit",
    unitAmountCents: 25000,
    currency: "usd",
    displayPrice: "$250 increments",
    quantityLabel: "$250 block",
    minQuantity: 1,
    maxQuantity: 4,
    requiresScheduling: true,
    fulfillment: "appointment",
    imagePath: "/procedure/xeomin.png",
    stripeProductKey: "wms_procedure_xeomin",
    stripePriceLookupKey: "wms_procedure_xeomin_block_250_v1",
    customerNote:
      "Xeomin is prepaid online in $250 blocks. The amount is applied to your treatment and any unused value remains as account credit.",
  },
  {
    slug: "filler",
    kind: "procedure",
    name: "Filler",
    shortDescription: "Charged per syringe.",
    pricingMode: "quantity",
    unitAmountCents: 70000,
    currency: "usd",
    displayPrice: "$700 per syringe",
    quantityLabel: "syringe",
    minQuantity: 1,
    maxQuantity: 10,
    requiresScheduling: true,
    fulfillment: "appointment",
    imagePath: "/procedure/filler.png",
    stripeProductKey: "wms_procedure_filler",
    stripePriceLookupKey: "wms_procedure_filler_700_v1",
  },
  {
    slug: "hyperhidrosis-treatment",
    kind: "procedure",
    name: "Hyperhidrosis Treatment",
    shortDescription: "Full upfront payment for one treatment visit.",
    pricingMode: "fixed",
    unitAmountCents: 100000,
    currency: "usd",
    displayPrice: "$1,000",
    quantityLabel: "treatment",
    minQuantity: 1,
    maxQuantity: 10,
    requiresScheduling: true,
    fulfillment: "appointment",
    imagePath: "/procedure/armpit.png",
    stripeProductKey: "wms_procedure_hyperhidrosis_treatment",
    stripePriceLookupKey: "wms_procedure_hyperhidrosis_treatment_1000_v1",
  },
  {
    slug: "blohmdahl-ear-piercing",
    kind: "procedure",
    name: "Blohmdahl Ear Piercing",
    shortDescription: "Charged per ear.",
    pricingMode: "quantity",
    unitAmountCents: 4500,
    currency: "usd",
    displayPrice: "$45 per ear",
    quantityLabel: "ear",
    minQuantity: 1,
    maxQuantity: 2,
    requiresScheduling: true,
    fulfillment: "appointment",
    imagePath: "/procedure/ear-piercing.png",
    stripeProductKey: "wms_procedure_blohmdahl_ear_piercing",
    stripePriceLookupKey: "wms_procedure_blohmdahl_ear_piercing_45_v1",
  },
  {
    slug: "co2-lift",
    kind: "product",
    name: "Co2 Lift",
    shortDescription: "Pickup-only medical-grade skincare product.",
    pricingMode: "fixed",
    unitAmountCents: 10000,
    currency: "usd",
    displayPrice: "$100",
    quantityLabel: "item",
    minQuantity: 1,
    maxQuantity: 10,
    requiresScheduling: false,
    fulfillment: "pickup",
    imagePath: "/product/c02-lift-pro.webp",
    stripeProductKey: "wms_product_co2_lift",
    stripePriceLookupKey: "wms_product_co2_lift_100_v1",
  },
  {
    slug: "co2-v-lift-for-women",
    kind: "product",
    name: "Co2 V Lift for Women",
    shortDescription: "Pickup-only intimate care product.",
    pricingMode: "fixed",
    unitAmountCents: 50000,
    currency: "usd",
    displayPrice: "$500",
    quantityLabel: "item",
    minQuantity: 1,
    maxQuantity: 10,
    requiresScheduling: false,
    fulfillment: "pickup",
    imagePath: "/product/c02-v-lift.webp",
    stripeProductKey: "wms_product_co2_v_lift_for_women",
    stripePriceLookupKey: "wms_product_co2_v_lift_for_women_500_v1",
  },
  {
    slug: "definage-clinical-power-trio-pro",
    kind: "product",
    name: "Definage Clinical Power Trio Pro",
    shortDescription: "Pickup-only medical-grade skincare product.",
    pricingMode: "fixed",
    unitAmountCents: 37000,
    currency: "usd",
    displayPrice: "$370",
    quantityLabel: "item",
    minQuantity: 1,
    maxQuantity: 10,
    requiresScheduling: false,
    fulfillment: "pickup",
    imagePath: "/product/defenage-power-pro.jpg",
    stripeProductKey: "wms_product_definage_clinical_power_trio_pro",
    stripePriceLookupKey: "wms_product_definage_clinical_power_trio_pro_370_v1",
  },
];

export const COMMERCE_CATALOG_BY_SLUG = Object.fromEntries(COMMERCE_CATALOG.map((item) => [item.slug, item])) as Record<
  string,
  CatalogItemConfig
>;

export const getCatalogConfigBySlug = (slug: string) =>
  COMMERCE_CATALOG_BY_SLUG[normalizeIntimacyProcedureSlug(slug)] || null;
